apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://sykepengesoknad.labs.nais.io/"
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.dev.nav.no"
    - name: SYFOREST_ROOT
      value: "https://tjenester-q1.nav.no/syforest"
    - name: LOGINSERVICE_URL
      value: "https://loginservice-q.nav.no/login"
    - name: AMPLITUDE_ENABLED
      value: "false"
    - name: MOCK_BACKEND
      value: "true"
    - name: DECORATOR_URL
      value: "https://www.nav.no/dekoratoren"
    - name: ENVIRONMENT
      value: "gcp"
    - name: SYKEFRAVAER_URL
      value: "https://ditt-sykefravaer.labs.nais.io/syk/sykefravaer"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
    - name: OPPLAERING
      value: "true"
