apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad
  namespace: default
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://tjenester.nav.no/sykepengesoknad"
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: SYFOSOKNAD_PROXY_ROOT
      value: "https://syfosoknad-proxy.nav.no"
    - name: SYFOREST_ROOT
      value: "https://tjenester.nav.no/syforest"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.nav.no/login"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://tjenester.nav.no/sykepengesoknad"
    - name: AMPLITUDE_KEY
      value: "d5b43a81941b61a3b06059197807a25a"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: DECORATOR_URL
      value: "https://www.nav.no/dekoratoren"
    - name: ENVIRONMENT
      value: "prod"
    - name: SYKEFRAVAER_URL
      value: "https://tjenester.nav.no/sykefravaer"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
