apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://www-gcp.dev.nav.no/syk/sykepengesoknad"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: syk/sykepengesoknad/api/internal/isAlive
  readiness:
    path: syk/sykepengesoknad/api/internal/isReady
  prometheus:
    enabled: true
    path: /syk/sykepengesoknad/api/internal/prometheus
  accessPolicy:
    outbound:
      rules:
        - application: sykepengesoknad-backend
        - application: flex-bucket-uploader
        - application: sykmeldinger-backend
          namespace: teamsykmelding
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.dev.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.dev.nav.no/login"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepengesoknad"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: ENVIRONMENT
      value: "q1"
    - name: SYKEFRAVAER_URL
      value: "https://www-gcp.dev.nav.no/syk/sykefravaer"
    - name: SYKMELDINGER_URL
      value: "https://www-gcp.dev.nav.no/syk/sykmeldinger"
    - name: DITTNAV_URL
      value: "https://www.dev.nav.no/person/dittnav/"
    - name: DECORATOR_ENV
      value: "dev"
    - name: DINESAKER_URL
      value: "https://person.dev.nav.no/mine-saker/tema/SYK"
    - name: ASSET_PREFIX
      value: "https://flex-static-files.dev.nav.no/sykepengesoknad"
    - name: VEDLIKEHOLD
      value: "false"
    - name: SYKMELDINGER_BACKEND_CLIENT_ID
      value: "dev-gcp:teamsykmelding:sykmeldinger-backend"
    - name: SYKEPENGESOKNAD_BACKEND_CLIENT_ID
      value: "dev-gcp:flex:sykepengesoknad-backend"
    - name: FLEX_BUCKET_UPLOADER_CLIENT_ID
      value: "dev-gcp:flex:flex-bucket-uploader"
