apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://sykepengesoknad.labs.nais.io/"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: syk/sykepengesoknad/api/isAlive
  readiness:
    path: syk/sykepengesoknad/api/isReady
  env:
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.dev.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice-q.nav.no/login"
    - name: AMPLITUDE_ENABLED
      value: "false"
    - name: MOCK_BACKEND
      value: "true"
    - name: ENVIRONMENT
      value: "gcp"
    - name: SYKEFRAVAER_URL
      value: "https://ditt-sykefravaer.labs.nais.io/syk/sykefravaer"
    - name: SYKMELDINGER_URL
      value: "https://sykmeldinger.labs.nais.io/syk/sykmeldinger"
    - name: DITTNAV_URL
      value: "https://flex-dittnav-brukertest.labs.nais.io/person/dittnav/?testperson=soknad"
    - name: OPPLAERING
      value: "true"
    - name: DECORATOR_ENV
      value: "prod"
    - name: DINESAKER_URL
      value: "https://person.nav.no/mine-saker/tema/SYK"
    - name: BACKEND_APP
      value: "syfosoknad"
    - name: VEDLIKEHOLD
      value: "false"
    - name: ABSOLUTT_TVANG
      value: "true"
