apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://www.nav.no/syk/sykepengesoknad"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: syk/sykepengesoknad/api/isAlive
  readiness:
    path: syk/sykepengesoknad/api/isReady
  env:
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.nav.no"
    - name: SYKMELDINGER_BACKEND_PROXY_ROOT
      value: "https://sykmelding-gateway.nav.no/sykmeldinger-backend"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.nav.no/login"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www.nav.no/syk/sykepengesoknad"
    - name: AMPLITUDE_KEY
      value: "d5b43a81941b61a3b06059197807a25a"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: ENVIRONMENT
      value: "prod"
    - name: SYKEFRAVAER_URL
      value: "https://www.nav.no/syk/sykefravaer"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
    - name: DECORATOR_ENV
      value: "prod"
    - name: DINESAKER_URL
      value: "https://person.nav.no/mine-saker/tema/SYK"
    - name: ASSET_PREFIX
      value: "https://flex-static-files.nav.no/sykepengesoknad"
    - name: BACKEND_APP
      value: "syfosoknad"
    - name: VEDLIKEHOLD
      value: "true"
