apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appname}}
  namespace: flex
  labels:
    team: flex
    branchState: {{ branchState }}
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - {{ ingress }}
  resources:
    limits:
      memory: 800Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: {{ replicas }}
    max: {{ replicas }}
  liveness:
    path: syk/sykepengesoknad/api/internal/isAlive
  readiness:
    path: syk/sykepengesoknad/api/internal/isReady
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  {{#if TTL_HOURS}}
  ttl: {{ TTL_HOURS }}
  {{/if}}

  env:
    - name: NO_DECORATOR
      value: "false"
    - name: TZ
      value: "Europe/Oslo"
