apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appname}}
  namespace: flex
  labels:
    team: flex
    branchState: {{ branchState }}
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ ingress }}
  resources:
    limits:
      memory: 800Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: {{ replicas }}
    max: {{ replicas }}
  liveness:
    path: syk/sykepengesoknad/api/internal/isAlive
  readiness:
    path: syk/sykepengesoknad/api/internal/isReady
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  # https://github.com/navikt/altinnkanal-2/blob/1b6a874294eb273602312c3494cd669ea9e94d9c/.nais/naiserator.yaml#L35
  {{#if TTL_HOURS}}
  ttl: {{ TTL_HOURS }}
  {{/if}}

  env:
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.dev.nav.no"
    - name: AMPLITUDE_ENABLED
      value: "false"
    - name: MOCK_BACKEND
      value: "true"
    - name: ENVIRONMENT
      value: "labs"
    - name: SYKEFRAVAER_URL
      value: "https://demo.ekstern.dev.nav.no/syk/sykefravaer"
    - name: SYKMELDINGER_URL
      value: "https://sykmeldinger.ekstern.dev.nav.no/syk/sykmeldinger"
    - name: MINSIDE_URL
      value: "https://www.dev.nav.no/minside/"
    - name: OPPLAERING
      value: "true"
    - name: DECORATOR_ENV
      value: "prod"
    - name: VEDLIKEHOLD
      value: "false"
    - name: ASSET_PREFIX
      value: "https://cdn.nav.no/flex/sykepengesoknad-frontend"
    - name: TZ
      value: "Europe/Oslo"
