ingress: https://www-gcp.dev.nav.no/syk/sykepengesoknad
env:
  AMPLITUDE_ENABLED: true
  ENVIRONMENT: q1
  SYKEFRAVAER_URL: https://www-gcp.dev.nav.no/syk/sykefravaer
  SYKMELDINGER_URL: https://www-gcp.dev.nav.no/syk/sykmeldinger
  MINSIDE_URL: https://www.dev.nav.no/minside/
  DECORATOR_ENV: dev
  ASSET_PREFIX: https://flex-static-files.dev.nav.no/sykepengesoknad
  VEDLIKEHOLD: false
  SYKMELDINGER_BACKEND_CLIENT_ID: dev-gcp:teamsykmelding:sykmeldinger-backend
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: dev-gcp:flex:sykepengesoknad-backend
  SYKEPENGESOKNAD_KVITTERINGER_CLIENT_ID: dev-gcp:flex:sykepengesoknad-kvitteringer
