apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appname}}
  namespace: flex
  labels:
    team: flex
    branchState: {{ branchState }}
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ ingress }}
  replicas:
    min: {{ replicas }}
    max: {{ replicas }}
  liveness:
    path: syk/sykepengesoknad/api/internal/isAlive
  readiness:
    path: syk/sykepengesoknad/api/internal/isReady
  env:
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.dev.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice-q.nav.no/login"
    - name: AMPLITUDE_ENABLED
      value: "false"
    - name: MOCK_BACKEND
      value: "true"
    - name: ENVIRONMENT
      value: "gcp"
    - name: SYKEFRAVAER_URL
      value: "https://ditt-sykefravaer.labs.nais.io/syk/sykefravaer"
    - name: SYKMELDINGER_URL
      value: "https://sykmeldinger.labs.nais.io/syk/sykmeldinger"
    - name: MINSIDE_URL
      value: "https://www.dev.nav.no/minside/"
    - name: OPPLAERING
      value: "true"
    - name: DECORATOR_ENV
      value: "prod"
    - name: VEDLIKEHOLD
      value: "false"
