apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad
  namespace: flex
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ingress}}
  replicas:
    min: 2
    max: 5
    cpuThresholdPercentage: 50
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  resources:
    limits:
      cpu: 2000m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi
  liveness:
    path: syk/sykepengesoknad/api/internal/isAlive
  readiness:
    path: syk/sykepengesoknad/api/internal/isReady
  prometheus:
    enabled: true
    path: /syk/sykepengesoknad/api/internal/prometheus
  accessPolicy:
    outbound:
      rules:
        - application: sykepengesoknad-backend
        - application: sykepengesoknad-kvitteringer
        - application: sykmeldinger-backend
          namespace: teamsykmelding
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}

