apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad
  namespace: flex
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
  labels:
    team: flex
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - {{ingress}}
  replicas:
    min: 2
    max: 5
    scalingStrategy:
      cpu:
        thresholdPercentage: 50
  preStopHook:
    http:
      path: syk/sykepengesoknad/api/internal/preStop
      port: 3000
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  observability:
    autoInstrumentation:
      enabled: false
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  liveness:
    path: syk/sykepengesoknad/api/internal/isAlive
  readiness:
    path: syk/sykepengesoknad/api/internal/isReady
  startup:
    path: syk/sykepengesoknad/api/internal/isAlive
    initialDelay: 30
  prometheus:
    enabled: true
    path: /syk/sykepengesoknad/api/internal/prometheus
  frontend:
    generatedConfig:
      mountPath: /usr/share/nginx/html/js/nais.js
  accessPolicy:
    outbound:
      rules:
        - application: sykepengesoknad-backend
        - application: sykepengesoknad-kvitteringer
        - application: flexjar-backend
        - application: sokos-kontoregister-person
          namespace: okonomi
        - application: sykmeldinger-backend
          namespace: teamsykmelding
        - application: nav-dekoratoren
          namespace: personbruker
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
  envFrom:
    - secret: sykepengesoknad-frontend-unleash-api-token
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}

