apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad
  namespace: flex
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  replicas:
    min: 2
    max: 5
    cpuThresholdPercentage: 50
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  liveness:
    path: syk/sykepengesoknad/api/internal/isAlive
  readiness:
    path: syk/sykepengesoknad/api/internal/isReady
  startup:
    path: syk/sykepengesoknad/api/internal/isAlive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /syk/sykepengesoknad/api/internal/prometheus
  accessPolicy:
    outbound:
      rules:
        - application: sykepengesoknad-backend
        - application: sykepengesoknad-kvitteringer
        - application: flex-hotjar-emotions
        - application: flexjar-backend
        - application: sokos-kontoregister-person
          namespace: okonomi
        - application: sykmeldinger-backend
          namespace: teamsykmelding
        - application: nav-dekoratoren
          namespace: personbruker
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}

