export const landlisteUtenforEøs = [
    'Afghanistan',
    'Albania',
    'Algerie',
    'Amerikansk Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antigua og Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Aserbajdsjan',
    'Australia',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia-Hercegovina',
    'Botswana',
    'Bouvetøya',
    'Brasil',
    'Britisk territorium i Indiahavet',
    'Brunei',
    'Burkina Faso',
    'Burma',
    'Burundi',
    'Canada',
    'Caymanøyene',
    'Chile',
    'Christmasøya',
    'Colombia',
    'Cookøyene',
    'Costa Rica',
    'Cuba',
    'Curaçao',
    'De forente arabiske emirater',
    'De okkuperte palestinske områdene',
    'Den dominikanske republikk',
    'Den sentralafrikanske republikk',
    'Djibouti',
    'Dominica',
    'Ecuador',
    'Egypt',
    'Ekvatorial-Guinea',
    'El Salvador',
    'Elfenbenskysten',
    'Eritrea',
    'Etiopia',
    'Falklandsøyene',
    'Fiji',
    'Filippinene',
    'Fransk Polynesia',
    'Færøyene',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Grenada',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard- og McDonald-øyene',
    'Honduras',
    'Hongkong',
    'Hviterussland',
    'India',
    'Indonesia',
    'Irak',
    'Iran',
    'Israel',
    'Jamaica',
    'Japan',
    'Jemen',
    'Jersey',
    'Jomfruøyene (Britisk)',
    'Jomfruøyene (USA)',
    'Jordan',
    'Kambodsja',
    'Kamerun',
    'Kapp Verde',
    'Karibisk Nederland',
    'Kasakhstan',
    'Kenya',
    'Kina',
    'Kirgisistan',
    'Kiribati',
    'Kokosøyene',
    'Komorene',
    'Kongo',
    'Kongo-Brazzaville',
    'Kosovo',
    'Kuwait',
    'Laos',
    'Lesotho',
    'Libanon',
    'Liberia',
    'Libya',
    'Macao',
    'Madagaskar',
    'Makedonia',
    'Malawi',
    'Malaysia',
    'Maldivene',
    'Mali',
    'Man',
    'Marokko',
    'Marshalløyene',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Mikronesiaføderasjonen',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Mosambik',
    'Namibia',
    'Nauru',
    'Nepal',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Nord-Korea',
    'Nord-Marianene',
    'Norfolk Island',
    'Ny-Caledonia',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua Ny-Guinea',
    'Paraguay',
    'Peru',
    'Pitcairn',
    'Puerto Rico',
    'Qatar',
    'Russland',
    'Rwanda',
    'Saint Kitts og Nevis',
    'Saint Lucia',
    'Saint Vincent og Grenadinene',
    'Saint-Barthélemy',
    'Saint-Martin',
    'Saint-Pierre-et-Miquelon',
    'Salomonøyene',
    'Samoa',
    'San Marino',
    'São Tomé og Príncipe',
    'Saudi-Arabia',
    'Senegal',
    'Serbia',
    'Seychellene',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Nederlandsk del)',
    'Somalia',
    'Sri Lanka',
    'St. Helena',
    'Storbritannia',
    'Sudan',
    'Surinam',
    'Swaziland',
    'Syria',
    'Sør-Afrika',
    'Sør-Georgia og de søre Sandwichøyene',
    'Sør-Korea',
    'Sør-Sudan',
    'Søre franske territorier',
    'Tadsjikistan',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad og Tobago',
    'Tsjad',
    'Tunisia',
    'Turkmenistan',
    'Turks- og Caicosøyene',
    'Tuvalu',
    'Tyrkia',
    'Uganda',
    'Ukraina',
    'Uruguay',
    'USA',
    'USA, mindre, utenforliggende øyer',
    'Usbekistan',
    'Vanuatu',
    'Vatikanstaten',
    'Venezuela',
    'Vest-Sahara',
    'Vietnam',
    'Wallis- og Futunaøyene',
    'Zambia',
    'Zimbabwe',
    'Øst-Timor',
]

export const landlisteEøs = [
    'Belgia',
    'Bulgaria',
    'Danmark',
    'Estland',
    'Finland',
    'Frankrike',
    'Hellas',
    'Irland',
    'Island',
    'Italia',
    'Kroatia',
    'Kypros',
    'Latvia',
    'Liechtenstein',
    'Litauen',
    'Luxembourg',
    'Malta',
    'Nederland',
    'Polen',
    'Portugal',
    'Romania',
    'Sveits',
    'Sverige',
    'Slovakia',
    'Slovenia',
    'Spania',
    'Tsjekkia',
    'Tyskland',
    'Ungarn',
    'Østerrike',
]
