const SporsmalTekster: any = {
    'nb': {
        'oppsummering.tittel': 'Oppsummering',

        'soknad.feilmelding.ja_nei_radio.lokal': 'Du må velge et alternativ',
        'soknad.feilmelding.checkbox.lokal': 'Du må velge et alternativ',
        'soknad.feilmelding.dato.lokal': 'Du må oppgi en dato',
        'soknad.feilmelding.periode.lokal': 'Du må oppgi periode',

        'soknad.feilmelding.ANSVARSERKLARING': 'Du må bekrefte dette før du går videre',
        'soknad.feilmelding.ANDRE_INNTEKTSKILDER': 'Du må svare på om du har andre inntektskilder eller arbeidsforhold',
        'soknad.feilmelding.ARBEID_UTENFOR_NORGE.lokal': 'Du må svare på om du har jobbet utenfor Norge',
        'soknad.feilmelding.ARBEIDSGIVER': 'Du må oppgi om du har arbeidsgiver',
        'soknad.feilmelding.ARBEID_UTENFOR_NORGE': 'Du må svare på om du har arbeidet i utlandet i løpet av de siste 12 månedene.',
        'soknad.feilmelding.BEKREFT_OPPLYSNINGER': 'Du må bekrefte at du har lest all informasjonen du har fått i søknaden og at opplysningene du har gitt er korrekte.',
        'soknad.feilmelding.BEKREFT_OPPLYSNINGER_UTLAND': 'Du må bekrefte at du oppfyller punktene over for å søke om å beholde sykepenger utenfor EØS',
        'soknad.feilmelding.BETALER_ARBEIDSGIVER': 'Du må svare på om arbeidsgiveren betaler lønnen din når du er syk',
        'soknad.feilmelding.FRAVER_FOR_BEHANDLING': 'Du må svare på om du brukte egenmeldinger eller var sykmeldt i denne perioden',
        'soknad.feilmelding.EGENMELDINGER': 'Du må svare på om du brukte egenmeldinger eller var sykmeldt i denne perioden',
        'soknad.feilmelding.TIDLIGERE_EGENMELDING': 'Du må svare på om du brukte egenmeldinger i denne perioden',
        'soknad.feilmelding.TIDLIGERE_PAPIRSYKMELDING': 'Du må svare på om du var sykmeldt før denne perioden',
        'soknad.feilmelding.EGENMELDINGER_NAR': 'Du må svare på om du var sykmeldt i denne perioden',
        'soknad.feilmelding.PAPIRSYKMELDING_NAR': 'Du må svare på om du var sykmeldt i denne perioden',
        'soknad.feilmelding.FERIE': 'Du må svare på om du skal ha ferie i hele perioden',
        'soknad.feilmelding.FERIE_V2': 'Du må svare på om du skal ha ferie i hele perioden',
        'soknad.feilmelding.PERMISJON': 'Du må svare på om du skal ha permisjon i hele perioden',
        'soknad.feilmelding.PERMISJON_V2': 'Du må svare på om du har hatt permisjon i denne perioden',
        'soknad.feilmelding.FERIE_PERMISJON_UTLAND': 'Du må svare på om har hatt ferie, permisjon eller oppholdt deg utenfor Norge i denne perioden',
        'soknad.feilmelding.FERIE_PERMISJON_UTLAND_HVA': 'Du må krysse av det som gjelder deg',
        'soknad.feilmelding.FULLTIDSSTUDIUM': 'Du må svare på om utdanningen er et fulltidsstudium',
        'soknad.feilmelding.HVILKE_ANDRE_INNTEKTSKILDER': 'Du må oppgi hvilke inntektskilder du har',
        'soknad.feilmelding.HVILKE_ANDRE_INNTEKTSKILDER.lokal': 'Du må velge minst et alternativ',

        'soknad.feilmelding.PERMITTERT_NAA': 'Du må svare på om du er permittert nå',
        'soknad.feilmelding.PERMITTERT_NAA.lokal': 'Du må svare på om du er permittert nå',
        'soknad.feilmelding.PERMITTERT_NAA_NAR': 'Du må svare på når du ble permittert',
        'soknad.feilmelding.PERMITTERT_PERIODE': 'Du må svare på om du har vært permittert',
        'soknad.feilmelding.PERMITTERT_PERIODE.lokal': 'Du må svare på om du har vært permittert',

        'soknad.feilmelding.HVOR_MANGE_TIMER': 'Du må svare på hvor mange timer du jobber normalt per uke',
        'soknad.feilmelding.HVOR_MANGE_TIMER.lokal': 'Du må oppgi antall timer',

        'soknad.feilmelding.HVOR_MANGE_TIMER_PER_UKE': 'Du må svare på hvor mange timer du jobbet per uke før du ble sykmeldt',

        'soknad.feilmelding.HVOR_MYE_HAR_DU_JOBBET': 'Du må svare på hvor mye du jobbet totalt',
        'soknad.feilmelding.HVOR_MYE_HAR_DU_JOBBET.lokal': 'Du må oppgi antall timer',

        'soknad.feilmelding.HVOR_MYE_PROSENT': 'Du må velge et alternativ',
        'soknad.feilmelding.HVOR_MYE_PROSENT_VERDI': 'Du må svare på hvor mye du jobbet totalt',
        'soknad.feilmelding.HVOR_MYE_PROSENT_VERDI.lokal': 'Du må oppgi prosent',

        'soknad.feilmelding.HVOR_MYE_TIMER': 'Du må velge et alternativ',
        'soknad.feilmelding.HVOR_MYE_TIMER_VERDI': 'Du må svare på hvor mye du jobbet totalt',
        'soknad.feilmelding.HVOR_MYE_TIMER_VERDI.lokal': 'Du må oppgi antall timer',
        'soknad.feilmelding.MINDRE_TIMER_ENN_FORVENTET.lokal': 'Timene du skrev inn tyder på at du har jobbet mindre enn %GRAD% %. Du må enten svare nei på spørsmålet over eller endre antall timer her.',
        'soknad.feilmelding.MINDRE_TIMER_ENN_FORVENTET': 'Timene du skrev inn tyder på at du har jobbet mindre enn %GRAD% %.',

        'soknad.feilmelding.TIDLIGERE_SYK': 'Du må svare på om du var syk med egenmelding eller papirsykmelding',
        'soknad.feilmelding.TIDLIGERE_SYK.lokal': 'Du må velge et av alternativene',

        'soknad.feilmelding.INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD_ER_DU_SYKMELDT': 'Du må svare på om du er sykmeldt fra andre arbeidsforhold',
        'soknad.feilmelding.INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD_ER_DU_SYKMELDT.lokal': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_ANNET_ER_DU_SYKMELDT': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_ANNET_ER_DU_SYKMELDT.lokal': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_ARBEIDSFORHOLD_ER_DU_SYKMELDT': 'Du må svare på om du er sykmeldt fra arbeidsforhold',
        'soknad.feilmelding.INNTEKTSKILDE_ARBEIDSFORHOLD_ER_DU_SYKMELDT.lokal': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_FRILANSER_ER_DU_SYKMELDT': 'Du må svare på om du er sykmeldt som frilanser',
        'soknad.feilmelding.INNTEKTSKILDE_FRILANSER_ER_DU_SYKMELDT.lokal': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_FRILANSER_SELVSTENDIG_ER_DU_SYKMELDT': 'Du må svare på om du er sykmeldt som frilanser eller selvstendig næringsdrivende',
        'soknad.feilmelding.INNTEKTSKILDE_FRILANSER_SELVSTENDIG_ER_DU_SYKMELDT.lokal': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT': 'Du må svare på om du er sykmeldt som jordbruker',
        'soknad.feilmelding.INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT.lokal': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA_ER_DU_SYKMELDT': 'Du må svare på om du er sykmeldt som dagmamma',
        'soknad.feilmelding.INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA_ER_DU_SYKMELDT.lokal': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_SELVSTENDIG_ER_DU_SYKMELDT': 'Du må svare på om du er sykmeldt som selvstendig næringsdrivende',
        'soknad.feilmelding.INNTEKTSKILDE_SELVSTENDIG_ER_DU_SYKMELDT.lokal': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_OMSORGSLONN_ER_DU_SYKMELDT': 'Du må svare på om du er sykmeldt med omsorgslønn',
        'soknad.feilmelding.INNTEKTSKILDE_OMSORGSLONN_ER_DU_SYKMELDT.lokal': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_FOSTERHJEM_ER_DU_SYKMELDT': 'Du må svare på om du er sykmeldt med fosterhjemgodtgjørelse',
        'soknad.feilmelding.INNTEKTSKILDE_FOSTERHJEM_ER_DU_SYKMELDT.lokal': 'Du må svare på om du er sykmeldt fra dette',

        'soknad.feilmelding.INNTEKTSKILDE_ARBEIDSFORHOLD': 'Du må svare på om du er sykmeldt fra arbeidsforhold',
        'soknad.feilmelding.INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD': 'Du må svare på om du er sykmeldt fra andre arbeidsforhold',
        'soknad.feilmelding.INNTEKTSKILDE_SELVSTENDIG': 'Du må svare på om du er sykmeldt som selvstendig næringsdrivende',
        'soknad.feilmelding.INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA': 'Du må svare på om du er sykmeldt som dagmamma',
        'soknad.feilmelding.INNTEKTSKILDE_JORDBRUKER': 'Du må svare på om du er sykmeldt som jordbruker',
        'soknad.feilmelding.INNTEKTSKILDE_FRILANSER': 'Du må svare på om du er sykmeldt som frilanser',
        'soknad.feilmelding.INNTEKTSKILDE_FRILANSER_SELVSTENDIG': 'Du må svare på om du er sykmeldt som frilanser eller selvstendig næringsdrivende',
        'soknad.feilmelding.INNTEKTSKILDE_ANNET': 'Du må svare på om du er sykmeldt fra dette',
        'soknad.feilmelding.INNTEKTSKILDE_OMSORGSLONN': 'Du må svare på om du er sykmeldt med omsorgslønn',
        'soknad.feilmelding.INNTEKTSKILDE_FOSTERHJEM': 'Du må svare på om du er sykmeldt med fosterhjemgodtgjørelse',

        'soknad.feilmelding.JOBBET_DU_100_PROSENT': 'Du må svare på om du jobbet noe i denne perioden',
        'soknad.feilmelding.JOBBET_DU_GRADERT': 'Vennligst svar på om du jobbet mer enn sykmeldingen tilsier',
        'soknad.feilmelding.LAND': 'Du må oppgi hvilket land du skal reise til',
        'soknad.feilmelding.LAND.max': 'Du kan maksimalt skrive inn %MAX% tegn her',
        'soknad.feilmelding.SYKMELDINGSGRAD': 'Du må oppgi om du er 100% sykmeldt',
        'soknad.feilmelding.TALL_MIN_MAX': 'Vennligst fyll ut et tall mellom %MIN% og %MAX%',
        'soknad.feilmelding.FRISKMELDT': 'Du må oppgi om du ble frisk iløpet av sykmeldingsperioden',
        'soknad.feilmelding.FRISKMELDT_START': 'Du må svare på når du ble frisk',
        'soknad.feilmelding.TILBAKE_I_ARBEID': 'Du må oppgi om du var tilbake i arbeid før friskmeldingsperioden utløp',
        'soknad.feilmelding.TILBAKE_NAR': 'Du må svare på når du var tilbake i arbeid.',
        'soknad.feilmelding.UTDANNING': 'Du må svare på om du har vært under utdanning i denne perioden',
        'soknad.feilmelding.UTDANNING_START': 'Du må svare på når du startet på utdanningen',
        'soknad.feilmelding.UTLAND': 'Du må svare på om du har oppholdt deg i utlandet i denne perioden',
        'soknad.feilmelding.UTLAND_V2': 'Du må svare på om du har vært utenfor EØS i denne perioden',
        'soknad.feilmelding.UTLAND_NAR': 'Du må svare på om du har oppholdt deg i utlandet i denne perioden',
        'soknad.feilmelding.UTLAND_NAR_V2': 'Du må svare på om du har vært utenfor EØS i denne perioden',
        'soknad.feilmelding.PERIODER': 'Du må svare på om du har vært utenfor EØS i denne perioden',
        'soknad.feilmelding.PERIODEUTLAND': 'Du må oppgi når du skal reise',
        'soknad.feilmelding.ARBEIDSLEDIG_UTLAND': 'Du må svare på om du har vært utenfor EØS i denne perioden',
        'soknad.feilmelding.UTLANDSOPPHOLD_SOKT_SYKEPENGER': 'Du må svare på om du har søkt om å beholde sykepenger under dette oppholdet utenfor Norge',
        'soknad.feilmelding.ENKELTSTAENDE_BEHANDLINGSDAGER_UKE': 'Du må oppgi hvilke dager du var til behandling',

        'soknad.hjelpetekst.FERIE_V2': 'Vi spør om ferie fordi du ikke kan få sykepenger og feriepenger samtidig. Tar du ferie, får du i stedet feriepenger.',
        'soknad.hjelpetekst.FERIE_NAR': 'Du må oppgi hvilke dager du hadde ferie',
        'soknad.hjelpetekst.FERIE_NAR_V2': 'Du må oppgi hvilke dager du hadde ferie',
        'soknad.hjelpetekst.PERMISJON_V2': 'Du må svare på om du tok ut permisjon',
        'soknad.hjelpetekst.PERMISJON_NAR': 'Du må oppgi hvilke dager du hadde permisjon',
        'soknad.hjelpetekst.PERMISJON_NAR_V2': 'Du må oppgi hvilke dager du hadde permisjon',
        'soknad.hjelpetekst.EGENMELDINGER' : 'Vi spør om dette for å kunne behandle søknaden din riktig. Egenmeldinger blir bare registrert hos arbeidsgiveren din, og eventuelle sykmeldinger på papir kan det ta litt tid for oss å registrere.',

        'soknad.infotekst.utlandsopphold_sokt_sykepenger.ja': 'Du må ha sendt en egen <a target="_blank" href="%URL%">utenlandssøknad</a> for å svare ja på dette spørsmålet. Husk at du også må fullføre denne søknaden om sykepenger.',
        'soknad.infotekst.utlandsopphold_sokt_sykepenger.nei': 'I utgangspunktet kan du bare få sykepenger mens du er i et land innenfor EØS. Du kan likevel <a href="%URL%" target="_blank">søke NAV om å få reise ut av EØS</a> og beholde sykepengene i en begrenset periode.',

        'sykepengesoknad.periodevelger.legg-til-ekstra': '+ Legg til ekstra periode',
        'sykepengesoknad.periodevelger.slett': 'Slett periode',
        'sykepengesoknad.periodevelger.fom': 'Fra og med',
        'sykepengesoknad.periodevelger.tom': 'Til og med',

        'soknad.presisering.INNTEKTSKILDE_ARBEIDSFORHOLD_ER_DU_SYKMELDT': 'Du må sende egen sykepengesøknad for dette. Det betyr også at legen må skrive en sykmelding for hvert arbeidsforhold du er sykmeldt fra.',
        'soknad.presisering.INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD_ER_DU_SYKMELDT': 'Du må sende egen sykepengesøknad for dette. Det betyr også at legen må skrive en sykmelding for hvert arbeidsforhold du er sykmeldt fra.',
        'soknad.presisering.INNTEKTSKILDE_SELVSTENDIG_ER_DU_SYKMELDT': 'Legen må sende inn én sykmelding for hver arbeidssituasjon du er sykmeldt fra, og du må søke om sykepenger for hver av dem.',
        'soknad.presisering.INNTEKTSKILDE_FRILANSER_ER_DU_SYKMELDT': 'Legen må sende inn én sykmelding for hver arbeidssituasjon du er sykmeldt fra, og du må søke om sykepenger for hver av dem.',
        'soknad.presisering.INNTEKTSKILDE_FRILANSER_SELVSTENDIG_ER_DU_SYKMELDT': 'Legen må sende inn én sykmelding for hver arbeidssituasjon du er sykmeldt fra, og du må søke om sykepenger for hver av dem.',
        'soknad.presisering.INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT': 'Legen må sende inn én sykmelding for hver arbeidssituasjon du er sykmeldt fra, og du må søke om sykepenger for hver av dem . Foreløpig støtter ikke den digitale løsningen søknad om sykepenger for disse gruppene. Søknaden om sykepenger for dette må du derfor sende på papir.',
        'soknad.presisering.INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA_ER_DU_SYKMELDT': 'Legen må sende inn én sykmelding for hver arbeidssituasjon du er sykmeldt fra, og du må søke om sykepenger for hver av dem.',
        'soknad.presisering.INNTEKTSKILDE_OMSORGSLONN_ER_DU_SYKMELDT': 'Legen må sende inn én sykmelding for hver arbeidssituasjon du er sykmeldt fra, og du må søke om sykepenger for hver av dem. Foreløpig støtter ikke den digitale løsningen søknad om sykepenger for omsorgslønn. Søknaden om sykepenger for dagmamma må du derfor sende på papir.',
        'soknad.presisering.INNTEKTSKILDE_FOSTERHJEM_ER_DU_SYKMELDT': 'Legen må sende inn én sykmelding for hver arbeidssituasjon du er sykmeldt fra, og du må søke om sykepenger for hver av dem. Foreløpig støtter ikke den digitale løsningen søknad om sykepenger for fosterhjem. Søknaden om sykepenger for dagmamma må du derfor sende på papir.',

    }, 'en': {}
}

export default SporsmalTekster
