export enum FeilaktigeOpplysninger {
    PERIODE = 'PERIODE',
    SYKMELDINGSGRAD = 'SYKMELDINGSGRAD',
    ARBEIDSGIVER = 'ARBEIDSGIVER',
    DIAGNOSE = 'DIAGNOSE',
    ANDRE = 'ANDRE'
}

export enum ForskuttererSvar {
    JA = 'JA',
    NEI = 'NEI',
    VET_IKKE = 'VET_IKKE'
}

export enum InntektskildeTyper {
    ANDRE_ARBEIDSFORHOLD = 'ANDRE_ARBEIDSFORHOLD',
    SELVSTENDIG_NAERINGSDRIVENDE = 'SELVSTENDIG_NAERINGSDRIVENDE',
    SELVSTENDIG_NAERINGSDRIVENDE_DAGMAMMA = 'SELVSTENDIG_NAERINGSDRIVENDE_DAGMAMMA',
    JORDBRUKER_FISKER_REINDRIFTSUTOEVER = 'JORDBRUKER_FISKER_REINDRIFTSUTOEVER',
    FRILANSER = 'FRILANSER',
    ANNET = 'ANNET'
}

export enum NokkelOpplysninger {
    STATUS = 'STATUS',
    INNSENDT_DATO = 'INNSENDT_DATO',
    ARBEIDSGIVER = 'ARBEIDSGIVER',
    ORGNUMMER = 'ORGNUMMER'
}

export enum SporsmalsTyper {
    ANSVAR_BEKREFTET = 'ANSVAR_BEKREFTET',
    EGENMELDINGSDAGER = 'EGENMELDINGSDAGER',
    GJENOPPTATT_ARBEID_FULLT_UT = 'GJENOPPTATT_ARBEID_FULLT_UT',
    FERIE_PERMISJON_UTENLANDSOPPHOLD = 'FERIE_PERMISJON_UTENLANDSOPPHOLD',
    AKTIVITET = 'AKTIVITET',
    INNTEKTSKILDER = 'INNTEKTSKILDER',
    UTDANNING = 'UTDANNING',
    ARBEIDSGIVER_FORSKUTTERER = 'ARBEIDSGIVER_FORSKUTTERER'
}

export enum SykepengesoknadSvartyper {
    CHECKBOX = 'CHECKBOX',
    RADIOKNAPPER = 'RADIOKNAPPER',
    TEKSTSVAR = 'TEKSTSVAR',
    DATO = 'DATO',
    DATOSPENN = 'DATOSPENN',
    HTML = 'HTML'
}

export type SykmeldingStatuser = 'NY' | 'SENDT' | 'UTGAATT' | 'AVBRUTT' | 'BEKREFTET' | 'TIL_SENDING'


export type AvgittAvTyper = 'TIDLIGERE_SOKNAD'


export enum TagTyper {
    ANDRE_INNTEKTSKILDER = 'ANDRE_INNTEKTSKILDER',
    ANSVARSERKLARING = 'ANSVARSERKLARING',
    ARBEID_UTENFOR_NORGE = 'ARBEID_UTENFOR_NORGE',
    ARBEIDSGIVER = 'ARBEIDSGIVER',
    ARBEIDSLEDIG_UTLAND = 'ARBEIDSLEDIG_UTLAND',
    BEKREFT_OPPLYSNINGER = 'BEKREFT_OPPLYSNINGER',
    BEKREFT_OPPLYSNINGER_UTLAND = 'BEKREFT_OPPLYSNINGER_UTLAND',
    BEKREFT_OPPLYSNINGER_UTLAND_INFO = 'BEKREFT_OPPLYSNINGER_UTLAND_INFO',
    BETALER_ARBEIDSGIVER = 'BETALER_ARBEIDSGIVER',
    EGENMELDINGER = 'EGENMELDINGER',
    EGENMELDINGER_NAR = 'EGENMELDINGER_NAR',
    ENKELTSTAENDE_BEHANDLINGSDAGER = 'ENKELTSTAENDE_BEHANDLINGSDAGER',
    ENKELTSTAENDE_BEHANDLINGSDAGER_UKE = 'ENKELTSTAENDE_BEHANDLINGSDAGER_UKE',
    ENKELTSTAENDE_BEHANDLINGSDAGER_DAG_NAR = 'ENKELTSTAENDE_BEHANDLINGSDAGER_DAG_NAR',
    FERIE = 'FERIE',
    FERIE_NAR = 'FERIE_NAR',
    FERIE_NAR_V2 = 'FERIE_NAR_V2',
    FERIE_PERMISJON_UTLAND = 'FERIE_PERMISJON_UTLAND',
    FERIE_PERMISJON_UTLAND_HVA = 'FERIE_PERMISJON_UTLAND_HVA',
    FERIE_V2 = 'FERIE_V2',
    FRAVER_FOR_BEHANDLING = 'FRAVER_FOR_BEHANDLING',
    FRISKMELDT = 'FRISKMELDT',
    FRISKMELDT_START = 'FRISKMELDT_START',
    FULLTIDSSTUDIUM = 'FULLTIDSSTUDIUM',
    HVILKE_ANDRE_INNTEKTSKILDER = 'HVILKE_ANDRE_INNTEKTSKILDER',
    HVOR_MANGE_TIMER = 'HVOR_MANGE_TIMER',
    HVOR_MANGE_TIMER_PER_UKE = 'HVOR_MANGE_TIMER_PER_UKE',
    HVOR_MYE_HAR_DU_JOBBET = 'HVOR_MYE_HAR_DU_JOBBET',
    HVOR_MYE_PROSENT = 'HVOR_MYE_PROSENT',
    HVOR_MYE_PROSENT_VERDI = 'HVOR_MYE_PROSENT_VERDI',
    HVOR_MYE_TIMER = 'HVOR_MYE_TIMER',
    HVOR_MYE_TIMER_VERDI = 'HVOR_MYE_TIMER_VERDI',
    IKKE_SOKT_UTENLANDSOPPHOLD_INFORMASJON = 'IKKE_SOKT_UTENLANDSOPPHOLD_INFORMASJON',
    INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD = 'INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD',
    INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD_ER_DU_SYKMELDT = 'INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD_ER_DU_SYKMELDT',
    INNTEKTSKILDE_ANNET = 'INNTEKTSKILDE_ANNET',
    INNTEKTSKILDE_ARBEIDSFORHOLD = 'INNTEKTSKILDE_ARBEIDSFORHOLD',
    INNTEKTSKILDE_ARBEIDSFORHOLD_ER_DU_SYKMELDT = 'INNTEKTSKILDE_ARBEIDSFORHOLD_ER_DU_SYKMELDT',
    INNTEKTSKILDE_FOSTERHJEM = 'INNTEKTSKILDE_FOSTERHJEM',
    INNTEKTSKILDE_FOSTERHJEM_ER_DU_SYKMELDT = 'INNTEKTSKILDE_FOSTERHJEM_ER_DU_SYKMELDT',
    INNTEKTSKILDE_FRILANSER = 'INNTEKTSKILDE_FRILANSER',
    INNTEKTSKILDE_FRILANSER_ER_DU_SYKMELDT = 'INNTEKTSKILDE_FRILANSER_ER_DU_SYKMELDT',
    INNTEKTSKILDE_FRILANSER_SELVSTENDIG = 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG',
    INNTEKTSKILDE_FRILANSER_SELVSTENDIG_ER_DU_SYKMELDT = 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG_ER_DU_SYKMELDT',
    INNTEKTSKILDE_JORDBRUKER = 'INNTEKTSKILDE_JORDBRUKER',
    INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT = 'INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT',
    INNTEKTSKILDE_OMSORGSLONN = 'INNTEKTSKILDE_OMSORGSLONN',
    INNTEKTSKILDE_OMSORGSLONN_ER_DU_SYKMELDT = 'INNTEKTSKILDE_OMSORGSLONN_ER_DU_SYKMELDT',
    INNTEKTSKILDE_SELVSTENDIG = 'INNTEKTSKILDE_SELVSTENDIG',
    INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA = 'INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA',
    INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA_ER_DU_SYKMELDT = 'INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA_ER_DU_SYKMELDT',
    INNTEKTSKILDE_SELVSTENDIG_ER_DU_SYKMELDT = 'INNTEKTSKILDE_SELVSTENDIG_ER_DU_SYKMELDT',
    JOBBET_DU_100_PROSENT = 'JOBBET_DU_100_PROSENT',
    JOBBET_DU_GRADERT = 'JOBBET_DU_GRADERT',
    LAND = 'LAND',
    PAPIRSYKMELDING_NAR = 'PAPIRSYKMELDING_NAR',
    PERIODER = 'PERIODER',
    PERIODEUTLAND = 'PERIODEUTLAND',
    PERMISJON = 'PERMISJON',
    PERMISJON_NAR = 'PERMISJON_NAR',
    PERMISJON_NAR_V2 = 'PERMISJON_NAR_V2',
    PERMISJON_V2 = 'PERMISJON_V2',
    PERMITTERT_NAA = 'PERMITTERT_NAA',
    PERMITTERT_NAA_NAR = 'PERMITTERT_NAA_NAR',
    PERMITTERT_PERIODE = 'PERMITTERT_PERIODE',
    PERMITTERT_PERIODE_NAR = 'PERMITTERT_PERIODE_NAR',
    SYKMELDINGSGRAD = 'SYKMELDINGSGRAD',
    TIDLIGERE_EGENMELDING = 'TIDLIGERE_EGENMELDING',
    TIDLIGERE_PAPIRSYKMELDING = 'TIDLIGERE_PAPIRSYKMELDING',
    TIDLIGERE_SYK = 'TIDLIGERE_SYK',
    TILBAKE_I_ARBEID = 'TILBAKE_I_ARBEID',
    TILBAKE_NAR = 'TILBAKE_NAR',
    UTDANNING = 'UTDANNING',
    UTDANNING_START = 'UTDANNING_START',
    UTLAND = 'UTLAND',
    UTLANDSOPPHOLD_SOKT_SYKEPENGER = 'UTLANDSOPPHOLD_SOKT_SYKEPENGER',
    UTLAND_NAR = 'UTLAND_NAR',
    UTLAND_NAR_V2 = 'UTLAND_NAR_V2',
    UTLAND_V2 = 'UTLAND_V2',
    VAER_KLAR_OVER_AT = 'VAER_KLAR_OVER_AT',

    // Reisetilskudd
    TRANSPORT_TIL_DAGLIG = 'TRANSPORT_TIL_DAGLIG',
    TYPE_TRANSPORT = 'TYPE_TRANSPORT',
    BIL_TIL_DAGLIG = 'BIL_TIL_DAGLIG',
    KM_HJEM_JOBB = 'KM_HJEM_JOBB',
    OFFENTLIG_TRANSPORT_TIL_DAGLIG = 'OFFENTLIG_TRANSPORT_TIL_DAGLIG',
    OFFENTLIG_TRANSPORT_BELOP = 'OFFENTLIG_TRANSPORT_BELOP',
    REISE_MED_BIL = 'REISE_MED_BIL',
    BIL_DATOER = 'BIL_DATOER',
    BIL_BOMPENGER = 'BIL_BOMPENGER',
    BIL_BOMPENGER_BELOP = 'BIL_BOMPENGER_BELOP',
    KVITTERINGER = 'KVITTERINGER',
    UTBETALING = 'UTBETALING',
}

export enum Steg {
    FOER_DU_BEGYNNER = 'FOER_DU_BEGYNNER',
    FRAVAER_OG_FRISKMELDING = 'FRAVAER_OG_FRISKMELDING',
    AKTIVITETER_I_SYKMELDINGSPERIODEN = 'AKTIVITETER_I_SYKMELDINGSPERIODEN',
    OPPSUMMERING = 'OPPSUMMERING',
    KVITTERING = 'KVITTERING',
    ETT_SPORSMAL_PER_SIDE = 'ETT_SPORSMAL_PER_SIDE'
}

export enum HotjarTriggerType {
    SOKNAD_ARBEIDSTAKER = 'SOKNAD_ARBEIDSTAKER',
    SOKNAD_FRILANSER_NAERINGSDRIVENDE = 'SOKNAD_FRILANSER_NAERINGSDRIVENDE',
    SOKNAD_OPPHOLD_UTENFOR_NORGE = 'SOKNAD_OPPHOLD_UTENFOR_NORGE',
    SELVSTENDIG_FRILANS_JULI_2018 = 'SELVSTENDIG_FRILANS_JULI_2018',
    SOKNAD_ARBEIDSLEDIG = 'SOKNAD_ARBEIDSLEDIG',
}

export const OPPHOLD_UTLAND_SKJEMA = 'OPPHOLD_UTLAND_SKJEMA'

export const getSoknadSkjemanavn = (id: string) => {
    return `SOKNAD___${id}`
}

export enum SvarEnums {
    JA = 'JA',
    NEI = 'NEI',
    CHECKED = 'CHECKED',
    UNCHECKED = 'UNCHECKED'
}

export enum SpmKomp {
    CHECKBOX_PANEL = 'CHECKBOX_PANEL',
    JA_NEI = 'JA_NEI',
    DATO = 'DATO',
    TALL = 'TALL',
}

