const TeaserTekster = {

    'soknad.teaser.status.AVBRUTT': 'Avbrutt av deg',
    'soknad.teaser.status.FREMTIDIG': 'Aktiveres %DATO%',
    'soknad.teaser.status.SENDT.til-arbeidsgiver-og-nav': 'Sendt til arbeidsgiver og NAV',
    'soknad.teaser.status.SENDT.til-arbeidsgiver': 'Sendt til arbeidsgiver',
    'soknad.teaser.status.SENDT.til-nav': 'Sendt til NAV',
    'soknad.teaser.status.UTGAATT': 'Utgått',
    'soknad.teaser.status.UTKAST_TIL_KORRIGERING': 'Utkast til endring',
    'soknader.teaser.fremtidig.modal.tittel' : 'Søknaden er ikke klar',
    'soknader.teaser.fremtidig.modal.tekst' : 'Du kan ikke fylle ut søknaden før denne sykmeldingsperioden er over %DATO%.',
    'soknader.teaser.fremtidig.modal.tekst2' : 'Du får en melding når søknaden er klar til å fylles ut.',
    'soknader.teaser.fremtidig.modal.utvidbar.tittel' : 'Hvorfor kan jeg ikke søke nå?',
    'soknader.teaser.fremtidig.modal.utvidbar.tekst' : 'For å utbetale riktig trenger vi å vite hva som skjedde i løpet av sykefraværet, for eksempel om du jobbet mer enn sykmeldingen sier, eller om du gjorde noe annet som har betydning for sykepengene dine.',
    'soknad.utland.teaser.tittel': 'Søknad om å beholde sykepenger utenfor EØS',
    'soknad.teaser.tittel': 'Søknad om sykepenger',
    'soknad.teaser.periode': 'Gjelder perioden %PERIODE%',
    'soknad.teaser.sykmeldt': '%GRAD%% sykmeldt',
    'soknad.teaser.sykmeldt-fra': '%GRAD%% sykmeldt fra %ARBEIDSGIVER%',
    'soknad.teaser.sykmeldt-behandlingsdager-fra': 'Sykmeldt fra %ARBEIDSGIVER%',
    'soknad.teaser.utgaatt.popup.header': 'Søknaden er utgått',
    'soknad.teaser.utgaatt.popup.innhold': 'Du får ikke åpnet denne søknaden fordi du ikke har sendt den innen fristen.',
    'soknad.reisetilskudd.teaser.tittel': 'Søknad om reisetilskudd',
    'om.sykepenger.tittel': 'Om sykepenger',
    'om.sykepenger.tekst1': 'Etter du har sendt sykmeldingen må du fylle ut og  sende søknaden om sykepenger før du kan få utbetalt sykepengene.',
    'om.sykepenger.tekst2': 'Den siste dagen i sykmeldingsperioden får du en melding. Da er søknaden om sykepenger klar, og du kan fylle den ut.',
    'om.sykepenger.hvorfor': 'Hvorfor må jeg søke om sykepenger?',
    'om.sykepenger.tekst3': 'I søknaden svarer du på noen spørsmål om hva som skjedde de dagene du var sykmeldt. Vi bruker svarene til å avgjøre hva du har krav på, og om det er NAV eller arbeidsgiveren din som skal betale. Disse opplysningene får vi foreløpig ikke innhentet automatisk.',
    'om.sykepenger.arbeidstakere.tittel': 'For arbeidstakere',
    'om.sykepenger.arbeidstakere.tekst1': 'De første 16 dagene er det arbeidsgiveren din som betaler sykepengene. Noen arbeidsgivere fortsetter å betale sykepenger, så får de pengene tilbake fra NAV senere.',
    'om.sykepenger.arbeidstakere.tekst2': 'Uansett må arbeidsgiveren din sende oss inntektsmelding. Den inneholder opplysninger om inntekten din, som vi må ha for å behandle søknaden.',
    'om.sykepenger.arbeidstakere.alertstripe': 'Hør gjerne med arbeidsgiveren din om inntektsmeldingen er sendt. Vi får ikke behandlet søknaden din før vi har den.',
    'om.sykepenger.selvstendige.tittel': 'For selvstendig næringsdrivende og frilansere',
    'om.sykepenger.selvstendige.tekst1': 'Har du tegnet <a href="">forsikring</a>, får du sykepenger fra første dag i sykefraværet. Du leverer søknaden om sykepenger etter sykmeldingsperioden. ',
    'om.sykepenger.selvstendige.tekst2': 'Har du ikke forsikring, får du sykepenger først etter 16 dager. Du trenger ikke levere søknad hvis sykefraværet er kortere enn 16 dager.',
    'om.sykepenger.selvstendige.tekst3': 'Du trenger ikke å levere søknaden om sykefraværet ditt ikke går over 16 dager.',
    'om.sykepenger.selvstendige.husk': 'Husk inntektsopplysninger',
    'om.sykepenger.selvstendige.tekst4': 'I tillegg til søknaden må du sende oss <a href="">skjemaet for inntektsopplysninger</a>.',
    'om.sykepenger.selvstendige.alertstripe': 'Viktig å huske på:<br />Vi får ikke behandlet søknaden før vi har fått inntekts&shy;opp&shy;lys&shy;ningene.',
    'om.sykepenger.tittel2': 'Skal du ut og reise?',
    'om.sykepenger.lenke1': 'Les om hva du må gjøre for å beholde sykepengene.',
    'om.sykepenger.lenke1.url': 'Les om hva du må gjøre for å beholde sykepengene.',
    'om.sykepenger.lenke2': 'Les mer om sykepenger her.',
    'om.sykepenger.lenke2.url': 'https://www.nav.no/no/nav-og-samfunn/kontakt-nav/utbetalinger/utbetalinger/utbetalingsdatoer-feriepenger-og-skattetrekk',
}

export default TeaserTekster
