import { arbeidsledig } from '../../../src/data/mock/data/opplaering'
import 'cypress-real-events'

xdescribe('Tester arbeidsledigsøknad', () => {
    const soknad = arbeidsledig

    before(() => {
        cy.visit('http://localhost:8080/syk/sykepengesoknad')
    })

    it('Laster startside', () => {
        cy.get('.navds-heading--xlarge').should('be.visible').and('have.text', 'Søknader')
        cy.get(`#soknader-list-til-behandling article a[href*=${soknad.id}]`).click()
    })

    it('Søknad ANSVARSERKLARING', () => {
        cy.url().should('include', `${soknad.id}/1`)
        cy.contains('1. april - 24. april 2020 • 24 dager')
        cy.contains('100% sykmeldt')
        cy.contains('Opplysninger fra sykmeldingen')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.focused().parent().parent().contains('Vi stoler på deg').should('have.css', 'box-shadow')
        cy.realPress('Space')
        cy.realPress('Tab')
        cy.focused().contains('Gå videre').should('have.css', 'box-shadow')
        cy.realPress('Enter')
        cy.contains('Friskmeldt')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Space')
        cy.realPress('Tab')
        cy.focused().contains('Gå videre').should('have.css', 'box-shadow')
        cy.realPress('Enter')
        cy.contains('Andre inntektskilder')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('{rightarrow}')
        cy.realPress('Tab')
        cy.focused().contains('Gå videre').should('have.css', 'box-shadow')
        cy.realPress('Enter')
        cy.contains('Utdanning')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('{rightarrow}')
        cy.realPress('Tab')
        cy.focused().contains('Gå videre').should('have.css', 'box-shadow')
        cy.realPress('Enter')
        cy.contains('Reise')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('{rightarrow}')
        cy.realPress('Tab')
        cy.focused().contains('Gå videre').should('have.css', 'box-shadow')
        cy.realPress('Enter')
        cy.contains('Til slutt')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.realPress('Tab')
        cy.focused()
            .parent()
            .contains(
                'Jeg har lest all informasjonen jeg har fått i søknaden og bekrefter at opplysningene jeg har gitt er korrekte.',
            )
        cy.focused().should('have.css', 'box-shadow')
        cy.realPress('Space')
        cy.realPress('Tab')
        cy.focused().contains('Send søknaden').should('have.css', 'box-shadow')
        cy.realPress('Enter')
        cy.contains('Søknaden er sendt til NAV')
        cy.contains('Mottatt')
    })
})
