export enum InntektsopplysningerDokumentType {
    SKATTEMELDING = 'SKATTEMELDING',
    SKATTEMELDING_OPTIONAL = 'SKATTEMELDING_OPTIONAL',
    NARINGSSPESIFIKASJON = 'NARINGSSPESIFIKASJON',
    NARINGSSPESIFIKASJON_OPTIONAL = 'NARINGSSPESIFIKASJON_OPTIONAL',
    REGNSKAP_FORRIGE_AAR = 'REGNSKAP_FORRIGE_AAR',
    REGNSKAP_FORELOPIG = 'REGNSKAP_FORELOPIG',
}
