export enum RSArbeidssituasjon {
    NAERINGSDRIVENDE = 'NAERINGSDRIVENDE',
    FRILANSER = 'FRILANSER',
    ARBEIDSTAKER = 'ARBEIDSTAKER',
    ARBEIDSLEDIG = 'ARBEIDSLEDIG',
    ANNET = 'ANNET',
}

export type RSArbeidssituasjonType = 'NAERINGSDRIVENDE' | 'FRILANSER' | 'ARBEIDSTAKER' | 'ARBEIDSLEDIG' | 'ANNET'
