export enum RSSvartype {
    JA_NEI = 'JA_NEI',
    CHECKBOX = 'CHECKBOX',
    CHECKBOX_GRUPPE = 'CHECKBOX_GRUPPE',
    CHECKBOX_PANEL = 'CHECKBOX_PANEL',
    DATO = 'DATO',
    PERIODE = 'PERIODE',
    PERIODER = 'PERIODER',
    TIMER = 'TIMER',
    FRITEKST = 'FRITEKST',
    LAND = 'LAND',
    IKKE_RELEVANT = 'IKKE_RELEVANT',
    PROSENT = 'PROSENT',
    RADIO_GRUPPE = 'RADIO_GRUPPE',
    RADIO_GRUPPE_TIMER_PROSENT = 'RADIO_GRUPPE_TIMER_PROSENT',
    RADIO = 'RADIO',
    TALL = 'TALL'
}
