export enum RSSoknadstype {
    SELVSTENDIGE_OG_FRILANSERE = 'SELVSTENDIGE_OG_FRILANSERE',
    OPPHOLD_UTLAND = 'OPPHOLD_UTLAND',
    ARBEIDSTAKERE = 'ARBEIDSTAKERE',
    ARBEIDSLEDIG = 'ARBEIDSLEDIG',
    BEHANDLINGSDAGER = 'BEHANDLINGSDAGER',
    ANNET_ARBEIDSFORHOLD = 'ANNET_ARBEIDSFORHOLD',
    REISETILSKUDD = 'REISETILSKUDD',
    GRADERT_REISETILSKUDD = 'GRADERT_REISETILSKUDD',
    FRISKMELDT_TIL_ARBEIDSFORMIDLING = 'FRISKMELDT_TIL_ARBEIDSFORMIDLING',
}

export type RSSoknadstypeType =
    | 'SELVSTENDIGE_OG_FRILANSERE'
    | 'OPPHOLD_UTLAND'
    | 'ARBEIDSTAKERE'
    | 'ARBEIDSLEDIG'
    | 'BEHANDLINGSDAGER'
    | 'ANNET_ARBEIDSFORHOLD'
    | 'REISETILSKUDD'
    | 'GRADERT_REISETILSKUDD'
    | 'FRISKMELDT_TIL_ARBEIDSFORMIDLING'
