export enum RSSvartype {
    RADIO_GRUPPE_UKEKALENDER = 'RADIO_GRUPPE_UKEKALENDER',
    BEHANDLINGSDAGER = 'BEHANDLINGSDAGER',
    INFO_BEHANDLINGSDAGER = 'INFO_BEHANDLINGSDAGER',
    CHECKBOX = 'CHECKBOX',
    CHECKBOX_GRUPPE = 'CHECKBOX_GRUPPE',
    CHECKBOX_PANEL = 'CHECKBOX_PANEL',
    DATO = 'DATO',
    FRITEKST = 'FRITEKST',
    IKKE_RELEVANT = 'IKKE_RELEVANT',
    JA_NEI = 'JA_NEI',
    LAND = 'LAND',
    PERIODE = 'PERIODE',
    PERIODER = 'PERIODER',
    PROSENT = 'PROSENT',
    RADIO = 'RADIO',
    RADIO_GRUPPE = 'RADIO_GRUPPE',
    RADIO_GRUPPE_TIMER_PROSENT = 'RADIO_GRUPPE_TIMER_PROSENT',
    TALL = 'TALL',
    TIMER = 'TIMER',
    KILOMETER = 'KILOMETER',
    BELOP = 'BELOP',
    DATOER = 'DATOER',
    KVITTERING = 'KVITTERING',
}

export type RSSvartypeType =
    'RADIO_GRUPPE_UKEKALENDER' |
    'BEHANDLINGSDAGER' |
    'INFO_BEHANDLINGSDAGER' |
    'CHECKBOX' |
    'CHECKBOX_GRUPPE' |
    'CHECKBOX_PANEL' |
    'DATO' |
    'FRITEKST' |
    'IKKE_RELEVANT' |
    'JA_NEI' |
    'LAND' |
    'PERIODE' |
    'PERIODER' |
    'PROSENT' |
    'RADIO' |
    'RADIO_GRUPPE' |
    'RADIO_GRUPPE_TIMER_PROSENT' |
    'TALL' |
    'TIMER' |
    'KILOMETER' |
    'BELOP' |
    'DATOER' |
    'KVITTERING'

