export enum RSSoknadstatus {
    NY = 'NY',
    SENDT = 'SENDT',
    FREMTIDIG = 'FREMTIDIG',
    UTKAST_TIL_KORRIGERING = 'UTKAST_TIL_KORRIGERING',
    KORRIGERT = 'KORRIGERT',
    AVBRUTT = 'AVBRUTT',
    SLETTET = 'SLETTET'
}
