const BjornTekster = {
    'soknad.bjorn.brukte_reisetilskuddet': 'Takk for svarene du har gitt om selve sykefraværet. <br /><br />Nå skal vi spørre deg om utgifter du har hatt til reiser til og fra jobben. Har du ikke hatt noen ekstrautgifter, svarer du bare nei og sender søknaden.',
    'soknad.bjorn.enkeltstaende_behandlingsdager': 'Du kan bare få én behandlingsdag i løpet av en uke. Trenger du flere slike dager, ber du legen om en gradert sykmelding i stedet.',
    'soknad.bjorn.ferie_v2': 'Et lite tips! Syns du det er vanskelig å svare på om du har tatt ut ferie eller ikke, finnes det en <a target="_blank" href="https://www.nav.no/no/person/arbeid/sykmeldt-arbeidsavklaringspenger-og-yrkesskade/papirsykmelding/hvorfor-spor-vi-om-ferie-i-soknaden-om-sykepenger">veiledning på nav.no</a>',
    'soknad.bjorn.fraver_for_behandling' : 'Vi trenger å vite om du har brukt egenmeldinger eller en papirsykmelding noen dager før denne sykmeldingen. Det er for å kunne beregne sykepengene dine riktig.',
    'soknad.bjorn.periodeutland' : 'Vil du beholde sykepengene mens du er på reise, kan du ikke være borte i mer enn 4 uker i løpet av en 12 måneders periode.',
    'soknad.bjorn.kvitteringer' : 'Du må laste opp kvitteringer hvis du har hatt ekstra utgifter til<br/> <ul> <li>taxi</li><li>offentlig transport</li><li>parkering</li></ul>Kvitteringene må kunne leses av en saksbehandler. Det tryggeste er å laste opp én kvittering om gangen.',
    'bekreft-sykmelding.skal-opprettes-soknad.bjorn': '<p>Du lurer kanskje på hvorfor du må søke som sykepenger på papir?</p>\n<p>Vi jobber med å digitalisere søknaden om sykepenger for selvstendig næringsdrivende og frilansere, men vi er dessverre ikke helt ferdige ennå.</p>',
    'sykepengesoknad.angi-tid.bjorn': 'Du har kanskje avtalt med arbeidsgiveren din at du skal ha færre arbeidsoppgaver, men bruke lenger tid på dem enn vanlig? Da svarer du i prosent hvor stor mengde av arbeidsoppgavene dine du har utført.',
    'sykepengesoknad.ferie.bjorn': 'Du lurer kanskje på hvorfor vi spør om ferie før du ble sykmeldt? Det er fordi vi må se om dette sykefraværet henger sammen med forrige periode du var syk.',
    'sykepengesoknad.sykmelding-utdrag.oppdelt.bjorn': 'Sykmeldingen din er lang, derfor er den delt opp i flere søknader om sykepenger. Da kan du søke før hele perioden er ferdig, slik at du slipper å vente lenge på sykepengene. Du vil få en ny SMS eller e-post når neste søknad er klar.',
    'sykepengesoknad-utland.bjorn': '<strong>Er du statsborger i et land utenfor EU/EØS?</strong><br />Skal du reise <strong>innenfor</strong> EU/EØS, må du benytte <a href="https://www.nav.no/soknader/nb/person/til-eller-fra-norge/opphold-eller-arbeid-utenfor-norge/NAV%2008-09.07/brev">søknaden på papir.</a>\n',
    'sykepengesoknad-utland.skjema.bjorn': 'Det er ikke mulig å ta ut ferie de dagene eller timene du skulle arbeidet og få utbetalt sykepenger for de andre. Men har du spart opp fleksitid, kan du avspasere dagene eller timene du skulle jobbet og få sykepenger for de andre dagene. Eksempel: Er du 50 prosent sykmeldt og ønsker å reise til utlandet noen dager, kan du avspasere halvparten av dagene. Har du ikke nok fleksitid å avspasere, må du ta ut hele feriedager.',
    'sykepengesoknad-utland.kvittering.sendt.bjorn': 'Nå har du bare søkt om å dra utenfor EØS, ikke om selve sykepengene. Det gjør du på vanlig måte senere, enten på papir eller digitalt.',
    'sykepengesoknad-utland.skjema.ferie-sporsmal-bjorn': 'Du får ikke sykepenger mens du har ferie. Det betyr at du ikke trenger å sende denne søknaden. God tur!',
}

export default BjornTekster
