export type MedlemskapSporsmalTag =
    | 'MEDLEMSKAP_OPPHOLD_UTENFOR_EOS'
    | 'MEDLEMSKAP_OPPHOLD_UTENFOR_NORGE'
    | 'MEDLEMSKAP_UTFORT_ARBEID_UTENFOR_NORGE'
    | 'MEDLEMSKAP_OPPHOLDSTILLATELSE'
    | 'MEDLEMSKAP_OPPHOLDSTILLATELSE_V2'
    | 'ARBEID_UTENFOR_NORGE'
