const OpplastingTekster = {
    'opplasting.her-kan': 'Last opp kvitteringer for reiseutgifter til og fra jobben fra %DATOER%.',
    'opplasting.legg-til': 'Legg til reiseutgift',
    'opplasting.hjelpetekst': 'Her skal du laste opp kvitteringer for transport du har brukt for å komme deg til jobb i  sykmeldingsperioden. Er du usikker på hvilken periode dette gjelder, kan du finne det under "Opplysninger om sykmeldingen" øverst på siden.',
    'opplasting_modal.tittel': 'Beløp',
    'opplasting_modal.nytt-utlegg.tittel': 'Legg til reiseutgift',
    'opplasting_modal.endre-utlegg.tittel': 'Endre reiseutgift',
    'opplasting_modal.belop.feilmelding': 'Du må skrive inn beløp',
    'opplasting_modal.dato': 'Dato for utgift',
    'opplasting_modal.dagensdato.feilmelding': 'Du må velge dato før dagens dato',
    'opplasting_modal.filopplasting.feilmelding': 'Du må laste opp kvittering',
    'opplasting_modal.transportmiddel.feilmelding': 'Du må velge transportmiddel',
    'opplasting_modal.feiloppsummering': 'For å gå videre må du rette opp følgende:',
    'opplasting_modal.filtyper': 'Tillatte filtyper er %FILTYPER%.',
    'opplasting_modal.maksfilstr': 'Maks bildestørrelse er %MAKSFILSTR%.',
    'opplasting_modal.bekreft': 'Bekreft',
    'opplasting_modal.slett': 'Slett',
    'opplasting_modal.vil-slette': 'Vil du slette kvitteringen?',
    'opplasting_modal.tilbake': 'Tilbake',
    'opplasting_modal.type-utgift.label': 'Type utgift',
    'opplasting_modal.endre-utlegg.hjelpetekst': 'Du kan foreløpig ikke redigere utgifter som du har lagt til. Men du kan slette den som er feil, og legge inn på nytt.',
    'soknad.info.kvitteringer-del1' : 'Du må laste opp kvitteringer hvis du har hatt ekstra utgifter til:',
    'soknad.info.kvitteringer-del2-kulepunkt1' : 'taxi',
    'soknad.info.kvitteringer-del2-kulepunkt2' : 'offentlig transport',
    'soknad.info.kvitteringer-del2-kulepunkt3' : 'parkering',
    'soknad.info.kvitteringer-del3' : 'Kvitteringene må kunne leses av en saksbehandler. Det tryggeste er å laste opp én kvittering om gangen.',
    'soknad.info.kvitteringer-PDF-tittel' : 'Fikk du kvitteringen som PDF?',
    'soknad.info.kvitteringer-PDF-tekst' : 'Vi klarer dessverre ikke å ta imot PDF, men du kan gjøre den om til et bilde. Du kan enten ta en skjermdump, eller du kan ta bilde av kvitteringen med telefonen.',
}

export default OpplastingTekster
