const landliste = [
    //TODO denne er fra chatgpt og trenger kvalitetssikring
    'Belgia',
    'Bulgaria',
    'Kroatia',
    'Kypros',
    'Tsjekkia',
    'Danmark',
    'Estland',
    'Finland',
    'Frankrike',
    'Tyskland',
    'Hellas',
    'Ungarn',
    'Island',
    'Irland',
    'Italia',
    'Latvia',
    'Liechtenstein',
    'Litauen',
    'Luxembourg',
    'Malta',
    'Nederland',
    'Polen',
    'Portugal',
    'Romania',
    'Slovakia',
    'Slovenia',
    'Spania',
    'Sverige',
    'Sveits',
    'Østerrike',
]

export default landliste
