name: 'Deploy unleash-token'
on:
  push:
    paths:
      - nais/unleash-token/**
      - .github/workflows/unleash-token.yml

jobs:
  deploy-unleash-token:
    uses: navikt/flex-github-actions-workflows/.github/workflows/nais-deploy-dev-og-prod.yml@main
    permissions:
      id-token: write
    with:
      app: ${{ github.event.repository.name }}-unleash
      nais-template: nais/unleash-token/unleash-token.yaml
    secrets: inherit
