name: 'Deploy unleash-token'
on:
  push:
    paths:
      - nais/unleash-token/**
      - .github/workflows/unleash-token.yml
jobs:
  deploy-unleash-token:
    name: Deploy unleash-token
    uses: navikt/flex-github-actions-workflows/.github/workflows/nais-deploy-dev-og-prod.yml@master
    with:
      image: 'n/a'
      app: 'n/a'
      nais-template: 'nais/unleash-token/unleash-token.yaml'
      prod-vars: 'nais/unleash-token/prod.yaml'
      dev-vars: 'nais/unleash-token/dev.yaml'
    secrets: inherit
