name: Demo delete
on: delete

jobs:
  branch-delete:
    uses: navikt/flex-github-actions-workflows/.github/workflows/demo-delete.yml@main
    permissions:
      id-token: write
    with:
      app: sykepengesoknad
      base-path: syk/sykepengesoknad
